export default [

    {spawnIsland: {
        assets: [ 
            {name: "Island",
            type: "glbModel",
            url: "models/islands/spawn island.glb",
            },
            {name: "interactiveObject",
            type: "glbModel",
            url: "models/interactive/spawn interactive object.glb",
            },
            {name: "colliderIsland",
            type: "glbModel",
            url: "models/colliders/spawn collider.glb",
            },
            {name: "Landscape",
                type: "glbModel",
                url: "models/landscape.glb",
            },
            {name: "Texture",
            type: "texture",
            url: "texture/textureSpawnIsland.webp",
            },
            {name : "SkyBox",
                type: "cubeTexture",
                url: [
                    "texture/skybox/px.png",
                    "texture/skybox/nx.png",
                    "texture/skybox/py.png",
                    "texture/skybox/ny.png",
                    "texture/skybox/pz.png",
                    "texture/skybox/nz.png",
                ],
            },
        ],
    },
    aboutMeIsland: {
        assets: [
            {name: "Island",
            type: "glbModel",
            url: "models/islands/about me island.glb",
            },
            {name: "interactiveObject",
            type: "glbModel",
            url: "models/interactive/about me interactive object.glb",
            },
            {name: "colliderIsland",
            type: "glbModel",
            url: "models/colliders/about me collider.glb",
            },
            {name: "Texture",
            type: "texture",
            url: "texture/textureAboutMeIsland.webp",},
            {name: "Video",
            type: "video",
            url: "video/AboutMeIslandVideo.mp4",},
        ],
    },
    projectsIsland: {
        assets: [
            {name: "Island",
            type: "glbModel",
            url: "models/islands/projects island.glb",
            },
            {name: "interactiveObject",
            type: "glbModel",
            url: "models/interactive/projects interactive object.glb",
            },
            {name: "colliderIsland",
            type: "glbModel",
            url: "models/colliders/projects collider.glb",
            },
            {name: "Texture",
            type: "texture",
            url: "texture/textureProjectIsland.webp",},
        ],
    },
    contactIsland: {
        assets: [
            {name: "Island",
            type: "glbModel",
            url: "models/islands/contact island.glb",
            },
            {name: "interactiveObject",
            type: "glbModel",
            url: "models/interactive/contact interactive object.glb",
            },
            {name: "colliderIsland",
            type: "glbModel",
            url: "models/colliders/contact collider.glb",
            },
            {name: "Texture",
            type: "texture",
            url: "texture/textureContactIsland.webp",},
        ],
    },
    hobbiesIsland: {
        assets: [
            {name: "Island",
            type: "glbModel",
            url: "models/islands/hobbies island.glb",
            },
            {name: "interactiveObject",
            type: "glbModel",
            url: "models/interactive/hobbies interactive object.glb",
            },
            {name: "colliderIsland",
            type: "glbModel",
            url: "models/colliders/hobbies collider.glb",
            },
            {name: "Texture",
            type: "texture",
            url: "texture/textureHobbiesIsland.webp",},
        ],
    },
}
]